export const likes = [
  {
    id: 1,
    title: "Xbox Series S",
    image: require("../assets/shopImages/sweet.jpg"),
    current_bid: "N1500",
    bids: 4,
    endingTime: "1:07:26",
    date_created: "24/05/2025",
  },
  {
    id: 2,
    title: "Laptop",
    image: require("../assets/shopImages/sweet.jpg"),
    current_bid: "N1500",
    bids: 4,
    endingTime: "0",
    date_created: "24/05/2025",
  },
  {
    id: 3,
    title: "Macbook Pro 16",
    image: require("../assets/shopImages/sweet.jpg"),
    current_bid: "N10000",
    bids: 4,
    endingTime: "0",
    date_created: "24/05/2025",
  },
  {
    id: 4,
    title: "Boat Headphones",
    image: require("../assets/shopImages/sweet.jpg"),
    current_bid: "N1500",
    bids: 4,
    endingTime: "1:07:26",
    date_created: "24/05/2025",
  },
  {
    id: 5,
    title: "Iphone 11 Pro",
    image: require("../assets/shopImages/sweet.jpg"),
    current_bid: "N1500",
    bids: 4,
    endingTime: "0",
    date_created: "24/05/2025",
  },
  {
    id: 6,
    title: "Xbox Series S",
    image: require("../assets/shopImages/sweet.jpg"),
    current_bid: "N1500",
    bids: 4,
    endingTime: "0",
    date_created: "24/05/2025",
  },
];
