export const sales = [
  {
    id: 1,
    title: "Xbox Series S",
    image: require("../assets/auctions/xbox.jpg"),
    price: "N1500",
    status: "Sold",
    date_created: "24/05/2025",
  },
  {
    id: 2,
    title: "Laptop",
    image: require("../assets/auctions/macbook.jpg"),
    price: "N1500",
    status: "Incomplete",
    date_created: "24/05/2025",
  },
  {
    id: 3,
    title: "Macbook Pro 16",
    image: require("../assets/auctions/macbook.jpg"),
    price: "N10000",
    status: "Sold",
    date_created: "24/05/2025",
  },
  {
    id: 4,
    title: "Boat Headphones",
    image: require("../assets/auctions/headphone.jpg"),
    price: "N1500",
    status: "Sold",
    date_created: "24/05/2025",
  },
  {
    id: 5,
    title: "Iphone 11 Pro",
    image: require("../assets/auctions/iphone.jpg"),
    price: "N1500",
    status: "Incomplete",
    date_created: "24/05/2025",
  },
  {
    id: 6,
    title: "Xbox Series S",
    image: require("../assets/auctions/xbox.jpg"),
    price: "N1500",
    status: "Sold",
    date_created: "24/05/2025",
  },
];
